name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latets
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to sohaib
        run: echo "helooo sohaib"
        
